# Generated by Django 3.1 on 2021-07-14 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20210713_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
